services:
  - type: web
    name: Farm-Connnect
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
